task:
  _target_: soviamate.tasks.codec.AudioCodecTask

  data:
    tokenizer: &tokenizer
      _target_: soviamate.datas.tokenizer.SentencePieceTokenizer
      model_path: tokenizers/libri_heavy_tokenizer.model
      vocab_size: &vocab_size 1025  # 1024 BPE tokens + 1 blank token (index 0)
      character_coverage: 0.9995
      model_type: bpe

    trainset:
      _target_: soviamate.datas.dataset.AudioCodecDataset
      filepaths: /data/Libri-Heavy/trainset.jsonl
      tokenizer: *tokenizer

    valset:
      _target_: soviamate.datas.dataset.AudioCodecDataset
      filepaths: /data/Libri-Heavy/valset.jsonl
      tokenizer: *tokenizer

    loader:
      batch_size: 24
      num_workers: 8
      pin_memory: true

  model:
    d_model: &d_model 1024
    speaker_dim: &speaker_dim 192

    hop_length: &hop_length 640
    frame_stacking: &frame_stacking 1

    dynamic_chunk_sizes: &dynamic_chunk_sizes [4, 8, 12, 16]
    full_context_prob: &full_context_prob 0.2

    audio_encoder:
      _target_: soviamate.modules.encoder.AudioEncoder
      frame_stacking: *frame_stacking
      hop_length: *hop_length
      num_layers: 4
      d_model: *d_model
      ffn_dim: 4096
      num_heads: 8
      kernel_size: 9
      dropout: 0.1
      dynamic_chunk_sizes: *dynamic_chunk_sizes
      full_context_prob: *full_context_prob

    text_decoder:
      _target_: soviamate.modules.decoder.TextDecoder
      input_dim: *d_model
      output_dim: *vocab_size
      hidden_dim: 4096
      num_layers: 2
      num_heads: 8
      kernel_size: 9
      dropout: 0.1
      dynamic_chunk_sizes: *dynamic_chunk_sizes
      full_context_prob: *full_context_prob

    audio_decoder:
      _target_: soviamate.modules.decoder.AudioDecoder
      frame_stacking: *frame_stacking
      hop_length: *hop_length
      num_layers: 4
      d_model: *d_model
      ffn_dim: 4096
      num_heads: 8
      kernel_size: 9
      dropout: 0.1
      dynamic_chunk_sizes: *dynamic_chunk_sizes
      full_context_prob: *full_context_prob
      speaker_dim: *speaker_dim

    audio_quantizer:
      _target_: soviamate.modules.quantizer.FiniteScalarQuantizer
      input_dim: *d_model
      fsq_levels: [5, 5, 5, 5, 5]
      noise_dropout: 0.5

    speaker_adapter:
      _target_: soviamate.modules.adapter.GlobalSpeakerAdapter
      sv_checkpoint: checkpoints/speaker_verification/campplus.bin
      sv_embedding_size: *speaker_dim
      sample_rate: 16000
      n_mels: 80

    timbre_grl:
      input_dim: *d_model
      hidden_dim: 512
      output_dim: *speaker_dim
      coef: 1.0

    discriminator:
      _target_: soviamate.modules.discriminator.AudioDiscriminator
      subband_periods: [2, 3, 5, 7, 11]
      subband_cutoffs: [0.253881, 0.170546, 0.103881, 0.075310, 0.049338]
      n_ffts: [512, 1024, 2048]
      win_lengths: [512, 1024, 2048]
      hop_lengths: [128, 256, 512]
      tier_strides: [2, 4, 8]

    audio_loss:
      _target_: soviamate.modules.criterion.MelSpectralEnergyDistanceLoss
      sample_rate: 16000
      window_sizes: [64, 128, 256, 512, 1024, 2048]
      mel_bins: [10, 20, 40, 80, 160, 320]

    adv_loss:
      _target_: soviamate.modules.criterion.LeastSquaresAdversarialLoss

    text_loss:
      _target_: soviamate.modules.criterion.SequenceToSequenceLoss
      zero_infinity: true

  optim:
    total_steps: &total_steps 1000000
    pct_start: &pct_start 0.01

    generator:
      optimizer:
        _target_: torch.optim.AdamW
        lr: 1.0
        betas: [0.9, 0.95]
        fused: true

      scheduler:
        _target_: torch.optim.lr_scheduler.OneCycleLR
        max_lr: 1e-5
        total_steps: *total_steps
        pct_start: *pct_start
        div_factor: 100
        final_div_factor: 1000

    discriminator:
      optimizer:
        _target_: torch.optim.AdamW
        lr: 1.0
        betas: [0.9, 0.95]
        fused: true

      scheduler:
        _target_: torch.optim.lr_scheduler.OneCycleLR
        max_lr: 1e-5
        total_steps: *total_steps
        pct_start: *pct_start
        div_factor: 100
        final_div_factor: 1000

callbacks:
  lr:
    _target_: lightning.pytorch.callbacks.LearningRateMonitor

  cb:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    filename: "{epoch}-{step}-{val_loss:.5f}"
    monitor: val_loss
    save_top_k: 10
    save_last: true
    every_n_train_steps: 100000

loggers:
  tb:
    _target_: lightning.pytorch.loggers.TensorBoardLogger
    save_dir: lightning_logs
    name: libri_heavy_codec
    version: null
    default_hp_metric: false

trainer:
  devices: 8
  accelerator: gpu
  precision: bf16-mixed
  strategy: ddp_find_unused_parameters_true
  max_epochs: 10
  val_check_interval: 50000
